#include <tree_sitter/api.h>
#include <tree_sitter/parser.h>
#include <tree_sitter/swift.h>
#include <tree_sitter/css.h>
#include <tree_sitter/go.h>
#include <tree_sitter/gomod.h>
#include <tree_sitter/html.h>
#include <tree_sitter/ruby.h>
#include <tree_sitter/java.h>
#include <tree_sitter/tree-sitter-json.h>
#include <tree_sitter/markdown.h>
#include <tree_sitter/php.h>
#include <tree_sitter/python.h>
